### ISSUE TITLE
Incompatibility with latest mono (and CoreFx)

### ISSUE THREAD

**Issue by EmilWine** [skbkontur/GroBuf#11]
Hi,
I came across an issue when serializing "Dictionary" class with GroBuf in Mono (which seems to actually use Dictionary.cs from CoreFx). As fasr as I could tell, some private fields underwent minor name changes e.g. "count" became "_count", "entries" became "_entries" etc... in [Dictionary.cs](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs)

This basically renders GroBuf unable to serialize Dictionaries for latest mono.
I'm using mono 5.14.0.177, with .net 4.5 in my project.
Thanks,
Emil

**Comment by AndrewKostousov** [comment]
Is this issue still reproduced on your version of Mono with the [latest version](https://www.nuget.org/packages/GroBuf/1.4.4) of GroBuf?

Recently we made some fixes which seem relevant. See [this](6383e2aa5eed14a51a12a2b353cd8b5408bf21fb) commit in particular. Fill free to reopen this issue in case your problem is not resolved.
